phrase:
  access_token: <access_token>
  project_id: <project_id>
  push:
    sources:
    - file: ./locales/<locale_name>.json
      params:
        update_translations: true
        file_format: i18next

  pull:
    targets:
    - file: ./locales/<locale_name>.json
      params:
        file_format: i18next
